on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: hubby
          path: target/hubby-1.0-SNAPSHOT.jar
